export const TEAM_LOGO_MAP = {
  // --- SEC ---
  alabama: "alabama-crimson-tide",
  "alabama crimson tide": "alabama-crimson-tide",
  arkansas: "arkansas-razorbacks",
  "arkansas razorbacks": "arkansas-razorbacks",
  auburn: "auburn-tigers",
  "auburn tigers": "auburn-tigers",
  florida: "florida-gators",
  "florida gators": "florida-gators",
  georgia: "georgia-bulldogs",
  "georgia bulldogs": "georgia-bulldogs",
  kentucky: "kentucky-wildcats",
  "kentucky wildcats": "kentucky-wildcats",
  lsu: "lsu-tigers",
  "lsu tigers": "lsu-tigers",
  "ole miss": "ole-miss-rebels",
  "ole miss rebels": "ole-miss-rebels",
  "mississippi state": "mississippi-state-bulldogs",
  "mississippi state bulldogs": "mississippi-state-bulldogs",
  missouri: "missouri-tigers",
  "missouri tigers": "missouri-tigers",
  oklahoma: "oklahoma-sooners",
  "oklahoma sooners": "oklahoma-sooners",
  "south carolina": "south-carolina-gamecocks",
  "south carolina gamecocks": "south-carolina-gamecocks",
  tennessee: "tennessee-volunteers",
  "tennessee volunteers": "tennessee-volunteers",
  texas: "texas-longhorns",
  "texas longhorns": "texas-longhorns",
  "texas a&m": "texas-a&m-aggies",
  "texas a&m aggies": "texas-a&m-aggies",
  vanderbilt: "vanderbilt-commodores",
  "vanderbilt commodores": "vanderbilt-commodores",

  // --- Big Ten ---
  illinois: "illinois-fighting-illini",
  "illinois fighting illini": "illinois-fighting-illini",
  indiana: "indiana-hoosiers",
  "indiana hoosiers": "indiana-hoosiers",
  iowa: "iowa-hawkeyes",
  "iowa hawkeyes": "iowa-hawkeyes",
  maryland: "maryland-terrapins",
  "maryland terrapins": "maryland-terrapins",
  michigan: "michigan-wolverines",
  "michigan wolverines": "michigan-wolverines",
  "michigan state": "michigan-state-spartans",
  "michigan state spartans": "michigan-state-spartans",
  minnesota: "minnesota-golden-gophers",
  "minnesota golden gophers": "minnesota-golden-gophers",
  nebraska: "nebraska-cornhuskers",
  "nebraska cornhuskers": "nebraska-cornhuskers",
  northwestern: "northwestern-wildcats",
  "northwestern wildcats": "northwestern-wildcats",
  "ohio state": "ohio-state-buckeyes",
  "ohio state buckeyes": "ohio-state-buckeyes",
  oregon: "oregon-ducks",
  "oregon ducks": "oregon-ducks",
  "penn state": "penn-state-nittany-lions",
  "penn state nittany lions": "penn-state-nittany-lions",
  purdue: "purdue-boilermakers",
  "purdue boilermakers": "purdue-boilermakers",
  rutgers: "rutgers-scarlet-knights",
  "rutgers scarlet knights": "rutgers-scarlet-knights",
  ucla: "ucla-bruins",
  "ucla bruins": "ucla-bruins",
  usc: "usc-trojans",
  "usc trojans": "usc-trojans",
  washington: "washington-huskies",
  "washington huskies": "washington-huskies",
  wisconsin: "wisconsin-badgers",
  "wisconsin badgers": "wisconsin-badgers",

  // --- ACC ---
  "boston college": "boston-college-eagles",
  "boston college eagles": "boston-college-eagles",
  california: "california-golden-bears",
  "california golden bears": "california-golden-bears",
  clemson: "clemson-tigers",
  "clemson tigers": "clemson-tigers",
  duke: "duke-blue-devils",
  "duke blue devils": "duke-blue-devils",
  "florida state": "florida-state-seminoles",
  "florida state seminoles": "florida-state-seminoles",
  "georgia tech": "georgia-tech-yellow-jackets",
  "georgia tech yellow jackets": "georgia-tech-yellow-jackets",
  louisville: "louisville-cardinals",
  "louisville cardinals": "louisville-cardinals",
  miami: "miami-hurricanes",
  "miami hurricanes": "miami-hurricanes",
  "north carolina": "north-carolina-tar-heels",
  "north carolina tar heels": "north-carolina-tar-heels",
  "nc state": "nc-state-wolfpack",
  "nc state wolfpack": "nc-state-wolfpack",
  pittsburgh: "pittsburgh-panthers",
  "pittsburgh panthers": "pittsburgh-panthers",
  smu: "smu-mustangs",
  "smu mustangs": "smu-mustangs",
  stanford: "stanford-cardinal",
  "stanford cardinal": "stanford-cardinal",
  syracuse: "syracuse-orange",
  "syracuse orange": "syracuse-orange",
  virginia: "virginia-cavaliers",
  "virginia cavaliers": "virginia-cavaliers",
  "virginia tech": "virginia-tech-hokies",
  "virginia tech hokies": "virginia-tech-hokies",
  "wake forest": "wake-forest-demon-deacons",
  "wake forest demon deacons": "wake-forest-demon-deacons",

  // --- Big 12 ---
  arizona: "arizona-wildcats",
  "arizona wildcats": "arizona-wildcats",
  "arizona state": "arizona-state-sun-devils",
  "arizona state sun devils": "arizona-state-sun-devils",
  baylor: "baylor-bears",
  "baylor bears": "baylor-bears",
  byu: "byu-cougars",
  "byu cougars": "byu-cougars",
  cincinnati: "cincinnati-bearcats",
  "cincinnati bearcats": "cincinnati-bearcats",
  colorado: "colorado-buffaloes",
  "colorado buffaloes": "colorado-buffaloes",
  houston: "houston-cougars",
  "houston cougars": "houston-cougars",
  "iowa state": "iowa-state-cyclones",
  "iowa state cyclones": "iowa-state-cyclones",
  kansas: "kansas-jayhawks",
  "kansas jayhawks": "kansas-jayhawks",
  "kansas state": "kansas-state-wildcats",
  "kansas state wildcats": "kansas-state-wildcats",
  "oklahoma state": "oklahoma-state-cowboys",
  "oklahoma state cowboys": "oklahoma-state-cowboys",
  tcu: "tcu-horned-frogs",
  "tcu horned frogs": "tcu-horned-frogs",
  "texas tech": "texas-tech-red-raiders",
  "texas tech red raiders": "texas-tech-red-raiders",
  ucf: "ucf-knights",
  "ucf knights": "ucf-knights",
  utah: "utah-utes",
  "utah utes": "utah-utes",
  "west virginia": "west-virginia-mountaineers",
  "west virginia mountaineers": "west-virginia-mountaineers",

  // --- American Athletic Conference ---
  army: "army-black-knights",
  "army black knights": "army-black-knights",
  charlotte: "charlotte-49ers",
  "charlotte 49ers": "charlotte-49ers",
  "east carolina": "east-carolina-pirates",
  "east carolina pirates": "east-carolina-pirates",
  fau: "florida-atlantic-owls",
  "florida atlantic owls": "florida-atlantic-owls",
  memphis: "memphis-tigers",
  "memphis tigers": "memphis-tigers",
  navy: "navy-midshipmen",
  "navy midshipmen": "navy-midshipmen",
  "north texas": "north-texas-mean-green",
  "north texas mean green": "north-texas-mean-green",
  rice: "rice-owls",
  "rice owls": "rice-owls",
  "south florida": "south-florida-bulls",
  "south florida bulls": "south-florida-bulls",
  temple: "temple-owls",
  "temple owls": "temple-owls",
  tulane: "tulane-green-wave",
  "tulane green wave": "tulane-green-wave",
  tulsa: "tulsa-golden-hurricane",
  "tulsa golden hurricane": "tulsa-golden-hurricane",
  uab: "uab-blazers",
  "uab blazers": "uab-blazers",
  utsa: "utsa-roadrunners",
  "utsa roadrunners": "utsa-roadrunners",

  // --- (Include other conferences as needed) ---
  "notre dame": "notre-dame-fighting-irish",
  "notre dame fighting irish": "notre-dame-fighting-irish",

  // --- Conference USA ---
  delaware: "delaware-fightin-blue-hens",
  "delaware fightin blue hens": "delaware-fightin-blue-hens",
  fiu: "fiu-panthers",
  "fiu panthers": "fiu-panthers",
  "jacksonville state": "jacksonville-state-gamecocks",
  "jacksonville state gamecocks": "jacksonville-state-gamecocks",
  "kennesaw state": "kennesaw-state-owls",
  "kennesaw state owls": "kennesaw-state-owls",
  liberty: "liberty-flames",
  "liberty flames": "liberty-flames",
  "louisiana tech": "louisiana-tech-bulldogs",
  "louisiana tech bulldogs": "louisiana-tech-bulldogs",
  "middle tennessee": "middle-tennessee-blue-raiders",
  "middle tennessee blue raiders": "middle-tennessee-blue-raiders",
  "new mexico state": "new-mexico-state-aggies",
  "new mexico state aggies": "new-mexico-state-aggies",
  "sam houston": "sam-houston-bearkats",
  "sam houston bearkats": "sam-houston-bearkats",
  utep: "utep-miners",
  "utep miners": "utep-miners",
  "western kentucky": "western-kentucky-hilltoppers",
  "western kentucky hilltoppers": "western-kentucky-hilltoppers",

  // --- MAC ---
  akron: "akron-zips",
  "akron zips": "akron-zips",
  "ball state": "ball-state-cardinals",
  "ball state cardinals": "ball-state-cardinals",
  "bowling green": "bowling-green-falcons",
  "bowling green falcons": "bowling-green-falcons",
  buffalo: "buffalo-bulls",
  "buffalo bulls": "buffalo-bulls",
  "central michigan": "central-michigan-chippewas",
  "central michigan chippewas": "central-michigan-chippewas",
  "eastern michigan": "eastern-michigan-eagles",
  "eastern michigan eagles": "eastern-michigan-eagles",
  "kent state": "kent-state-golden-flashes",
  "kent state golden flashes": "kent-state-golden-flashes",
  "miami (oh)": "miami-oh-redhawks",
  "miami (oh) redhawks": "miami-oh-redhawks",
  "northern illinois": "northern-illinois-huskies",
  "northern illinois huskies": "northern-illinois-huskies",
  ohio: "ohio-bobcats",
  "ohio bobcats": "ohio-bobcats",
  toledo: "toledo-rockets",
  "toledo rockets": "toledo-rockets",
  "western michigan": "western-michigan-broncos",
  "western michigan broncos": "western-michigan-broncos",

  // --- Mountain West ---
  "air force": "air-force-falcons",
  "air force falcons": "air-force-falcons",
  "boise state": "boise-state-broncos",
  "boise state broncos": "boise-state-broncos",
  "colorado state": "colorado-state-rams",
  "colorado state rams": "colorado-state-rams",
  "fresno state": "fresno-state-bulldogs",
  "fresno state bulldogs": "fresno-state-bulldogs",
  hawaii: "hawaii-rainbow-warriors",
  "hawaii rainbow warriors": "hawaii-rainbow-warriors",
  nevada: "nevada-wolf-pack",
  "nevada wolf pack": "nevada-wolf-pack",
  "new mexico": "new-mexico-lobos",
  "new mexico lobos": "new-mexico-lobos",
  "san diego state": "san-diego-state-aztecs",
  "san diego state aztecs": "san-diego-state-aztecs",
  "san jose state": "san-jose-state-spartans",
  "san jose state spartans": "san-jose-state-spartans",
  unlv: "unlv-rebels",
  "unlv rebels": "unlv-rebels",
  "utah state": "utah-state-aggies",
  "utah state aggies": "utah-state-aggies",
  wyoming: "wyoming-cowboys",
  "wyoming cowboys": "wyoming-cowboys",

  // --- Pac-12 ---
  "oregon state": "oregon-state-beavers",
  "oregon state beavers": "oregon-state-beavers",
  "washington state": "washington-state-cougars",
  "washington state cougars": "washington-state-cougars",

  // --- Sun Belt ---
  "appalachian state": "appalachian-state-mountaineers",
  "appalachian state mountaineers": "appalachian-state-mountaineers",
  "arkansas state": "arkansas-state-red-wolves",
  "arkansas state red wolves": "arkansas-state-red-wolves",
  "coastal carolina": "coastal-carolina-chanticleers",
  "coastal carolina chanticleers": "coastal-carolina-chanticleers",
  "georgia southern": "georgia-southern-eagles",
  "georgia southern eagles": "georgia-southern-eagles",
  "georgia state": "georgia-state-panthers",
  "georgia state panthers": "georgia-state-panthers",
  "james madison": "james-madison-dukes",
  "james madison dukes": "james-madison-dukes",
  louisiana: "louisiana-ragin-cajuns",
  "louisiana ragin cajuns": "louisiana-ragin-cajuns",
  ulm: "ulm-warhawks",
  "ulm warhawks": "ulm-warhawks",
  marshall: "marshall-thundering-herd",
  "marshall thundering herd": "marshall-thundering-herd",
  "old dominion": "old-dominion-monarchs",
  "old dominion monarchs": "old-dominion-monarchs",
  "south alabama": "south-alabama-jaguars",
  "south alabama jaguars": "south-alabama-jaguars",
  "southern miss": "southern-miss-golden-eagles",
  "southern miss golden eagles": "southern-miss-golden-eagles",
  "texas state": "texas-state-bobcats",
  "texas state bobcats": "texas-state-bobcats",
  troy: "troy-trojans",
  "troy trojans": "troy-trojans",

  // --- Patriot League ---
  bucknell: "bucknell-bison",
  "bucknell bison": "bucknell-bison",
  colgate: "colgate-raiders",
  "colgate raiders": "colgate-raiders",
  fordham: "fordham-rams",
  "fordham rams": "fordham-rams",
  georgetown: "georgetown-hoyas",
  "georgetown hoyas": "georgetown-hoyas",
  "holy cross": "holy-cross-crusaders",
  "holy cross crusaders": "holy-cross-crusaders",
  lafayette: "lafayette-leopards",
  "lafayette leopards": "lafayette-leopards",
  lehigh: "lehigh-mountain-hawks",
  "lehigh mountain hawks": "lehigh-mountain-hawks",

  // --- Big Sky ---
  "cal poly": "cal-poly-mustangs",
  "cal poly mustangs": "cal-poly-mustangs",
  "eastern washington": "eastern-washington-eagles",
  "eastern washington eagles": "eastern-washington-eagles",
  idaho: "idaho-vandals",
  "idaho vandals": "idaho-vandals",
  "idaho state": "idaho-state-bengals",
  "idaho state bengals": "idaho-state-bengals",
  montana: "montana-grizzlies",
  "montana grizzlies": "montana-grizzlies",
  "montana state": "montana-state-bobcats",
  "montana state bobcats": "montana-state-bobcats",
  "northern arizona": "northern-arizona-lumberjacks",
  "northern arizona lumberjacks": "northern-arizona-lumberjacks",
  "northern colorado": "northern-colorado-bears",
  "northern colorado bears": "northern-colorado-bears",
  "portland state": "portland-state-vikings",
  "portland state vikings": "portland-state-vikings",
  "sacramento state": "sacramento-state-hornets",
  "sacramento state hornets": "sacramento-state-hornets",
  "uc davis": "uc-davis-aggies",
  "uc davis aggies": "uc-davis-aggies",
  "weber state": "weber-state-wildcats",
  "weber state wildcats": "weber-state-wildcats",

  // --- Coastal Athletic Association (CAA) ---
  albany: "albany-great-danes",
  "albany great danes": "albany-great-danes",
  bryant: "bryant-bulldogs",
  "bryant bulldogs": "bryant-bulldogs",
  campbell: "campbell-fighting-camels",
  "campbell fighting camels": "campbell-fighting-camels",
  delaware: "delaware-fightin-blue-hens",
  "delaware fightin blue hens": "delaware-fightin-blue-hens",
  elon: "elon-phoenix",
  "elon phoenix": "elon-phoenix",
  hampton: "hampton-pirates",
  "hampton pirates": "hampton-pirates",
  maine: "maine-black-bears",
  "maine black bears": "maine-black-bears",
  monmouth: "monmouth-hawks",
  "monmouth hawks": "monmouth-hawks",
  "new hampshire": "new-hampshire-wildcats",
  "new hampshire wildcats": "new-hampshire-wildcats",
  "rhode island": "rhode-island-rams",
  "rhode island rams": "rhode-island-rams",
  richmond: "richmond-spiders",
  "richmond spiders": "richmond-spiders",
  "stony brook": "stony-brook-seawolves",
  "stony brook seawolves": "stony-brook-seawolves",
  towson: "towson-tigers",
  "towson tigers": "towson-tigers",
  villanova: "villanova-wildcats",
  "villanova wildcats": "villanova-wildcats",
  "william & mary": "william-mary-tribe",
  "william & mary tribe": "william-mary-tribe",

  // --- Coastal Athletic Association (CAA) ---
  albany: "albany-great-danes",
  "albany great danes": "albany-great-danes",
  bryant: "bryant-bulldogs",
  "bryant bulldogs": "bryant-bulldogs",
  campbell: "campbell-fighting-camels",
  "campbell fighting camels": "campbell-fighting-camels",
  delaware: "delaware-fightin-blue-hens",
  "delaware fightin blue hens": "delaware-fightin-blue-hens",
  elon: "elon-phoenix",
  "elon phoenix": "elon-phoenix",
  hampton: "hampton-pirates",
  "hampton pirates": "hampton-pirates",
  maine: "maine-black-bears",
  "maine black bears": "maine-black-bears",
  monmouth: "monmouth-hawks",
  "monmouth hawks": "monmouth-hawks",
  "new hampshire": "new-hampshire-wildcats",
  "new hampshire wildcats": "new-hampshire-wildcats",
  "rhode island": "rhode-island-rams",
  "rhode island rams": "rhode-island-rams",
  richmond: "richmond-spiders",
  "richmond spiders": "richmond-spiders",
  "stony brook": "stony-brook-seawolves",
  "stony brook seawolves": "stony-brook-seawolves",
  towson: "towson-tigers",
  "towson tigers": "towson-tigers",
  villanova: "villanova-wildcats",
  "villanova wildcats": "villanova-wildcats",
  "william & mary": "william-mary-tribe",
  "william & mary tribe": "william-mary-tribe",

  // --- Ivy League ---
  brown: "brown-bears",
  "brown bears": "brown-bears",
  columbia: "columbia-lions",
  "columbia lions": "columbia-lions",
  cornell: "cornell-big-red",
  "cornell big red": "cornell-big-red",
  dartmouth: "dartmouth-big-green",
  "dartmouth big green": "dartmouth-big-green",
  harvard: "harvard-crimson",
  "harvard crimson": "harvard-crimson",
  penn: "penn-quakers",
  "penn quakers": "penn-quakers",
  princeton: "princeton-tigers",
  "princeton tigers": "princeton-tigers",
  yale: "yale-bulldogs",
  "yale bulldogs": "yale-bulldogs",

  // --- MEAC ---
  "delaware state": "delaware-state-hornets",
  "delaware state hornets": "delaware-state-hornets",
  howard: "howard-bison",
  "howard bison": "howard-bison",
  "morgan state": "morgan-state-bears",
  "morgan state bears": "morgan-state-bears",
  "norfolk state": "norfolk-state-spartans",
  "norfolk state spartans": "norfolk-state-spartans",
  "north carolina central": "north-carolina-central-eagles",
  "north carolina central eagles": "north-carolina-central-eagles",
  "south carolina state": "south-carolina-state-bulldogs",
  "south carolina state bulldogs": "south-carolina-state-bulldogs",

  // --- MVFC ---
  "illinois state": "illinois-state-redbirds",
  "illinois state redbirds": "illinois-state-redbirds",
  "indiana state": "indiana-state-sycamores",
  "indiana state sycamores": "indiana-state-sycamores",
  "missouri state": "missouri-state-bears",
  "missouri state bears": "missouri-state-bears",
  "murray state": "murray-state-racers",
  "murray state racers": "murray-state-racers",
  "north dakota": "north-dakota-fighting-hawks",
  "north dakota fighting hawks": "north-dakota-fighting-hawks",
  "north dakota state": "north-dakota-state-bison",
  "north dakota state bison": "north-dakota-state-bison",
  "northern iowa": "northern-iowa-panthers",
  "northern iowa panthers": "northern-iowa-panthers",
  "south dakota": "south-dakota-coyotes",
  "south dakota coyotes": "south-dakota-coyotes",
  "south dakota state": "south-dakota-state-jackrabbits",
  "south dakota state jackrabbits": "south-dakota-state-jackrabbits",
  "southern illinois": "southern-illinois-salukis",
  "southern illinois salukis": "southern-illinois-salukis",
  "youngstown state": "youngstown-state-penguins",
  "youngstown state penguins": "youngstown-state-penguins",

  // --- NEC ---
  "central connecticut state": "central-connecticut-state-blue-devils",
  "central connecticut state blue devils":
    "central-connecticut-state-blue-devils",
  duquesne: "duquesne-dukes",
  "duquesne dukes": "duquesne-dukes",
  liu: "liu-sharks",
  "liu sharks": "liu-sharks",
  mercyhurst: "mercyhurst-lakers",
  "mercyhurst lakers": "mercyhurst-lakers",
  "robert morris": "robert-morris-colonials",
  "robert morris colonials": "robert-morris-colonials",
  "saint francis": "saint-francis-red-flash",
  "saint francis red flash": "saint-francis-red-flash",
  stonehill: "stonehill-skyhawks",
  "stonehill skyhawks": "stonehill-skyhawks",
  wagner: "wagner-seahawks",
  "wagner seahawks": "wagner-seahawks",

  // --- Pioneer Football League ---
  butler: "butler-bulldogs",
  "butler bulldogs": "butler-bulldogs",
  davidson: "davidson-wildcats",
  "davidson wildcats": "davidson-wildcats",
  dayton: "dayton-flyers",
  "dayton flyers": "dayton-flyers",
  drake: "drake-bulldogs",
  "drake bulldogs": "drake-bulldogs",
  marist: "marist-red-foxes",
  "marist red foxes": "marist-red-foxes",
  "morehead state": "morehead-state-eagles",
  "morehead state eagles": "morehead-state-eagles",
  presbyterian: "presbyterian-blue-hose",
  "presbyterian blue hose": "presbyterian-blue-hose",
  "san diego": "san-diego-toreros",
  "san diego toreros": "san-diego-toreros",
  stetson: "stetson-hatters",
  "stetson hatters": "stetson-hatters",
  "st. thomas": "st-thomas-tommies",
  "st. thomas tomies": "st-thomas-tommies",
  valparaiso: "valparaiso-beacons",
  "valparaiso beacons": "valparaiso-beacons",

  // --- Southern Conference ---
  chattanooga: "chattanooga-mocs",
  "chattanooga mocs": "chattanooga-mocs",
  "east tennessee state": "east-tennessee-state-buccaneers",
  "east tennessee state buccaneers": "east-tennessee-state-buccaneers",
  furman: "furman-paladins",
  "furman paladins": "furman-paladins",
  mercer: "mercer-bears",
  "mercer bears": "mercer-bears",
  samford: "samford-bulldogs",
  "samford bulldogs": "samford-bulldogs",
  "the citadel": "the-citadel-bulldogs",
  "the citadel bulldogs": "the-citadel-bulldogs",
  vmi: "vmi-keydets",
  "vmi keydets": "vmi-keydets",
  "western carolina": "western-carolina-catamounts",
  "western carolina catamounts": "western-carolina-catamounts",
  wofford: "wofford-terriers",
  "wofford terriers": "wofford-terriers",

  // --- Southland Conference ---
  "houston christian": "houston-christian-huskies",
  "houston christian huskies": "houston-christian-huskies",
  "incarnate word": "incarnate-word-cardinals",
  "incarnate word cardinals": "incarnate-word-cardinals",
  lamar: "lamar-cardinals",
  "lamar cardinals": "lamar-cardinals",
  mcneese: "mcneese-cowboys",
  "mcneese cowboys": "mcneese-cowboys",
  nicholls: "nicholls-colonels",
  "nicholls colonels": "nicholls-colonels",
  "northwestern state": "northwestern-state-demons",
  "northwestern state demons": "northwestern-state-demons",
  "southeastern louisiana": "southeastern-louisiana-lions",
  "southeastern louisiana lions": "southeastern-louisiana-lions",
  "stephen f. austin": "stephen-f-austin-lumberjacks",
  "stephen f. austin lumberjacks": "stephen-f-austin-lumberjacks",
  "texas a&m-commerce": "texas-a&m-commerce-lions",
  "texas a&m-commerce lions": "texas-a&m-commerce-lions",

  // --- SWAC ---
  "alabama a&m": "alabama-a&m-bulldogs",
  "alabama a&m bulldogs": "alabama-a&m-bulldogs",
  "alabama state": "alabama-state-hornets",
  "alabama state hornets": "alabama-state-hornets",
  "alcorn state": "alcorn-state-braves",
  "alcorn state braves": "alcorn-state-braves",
  "arkansas-pine bluff": "arkansas-pine-bluff-golden-lions",
  "arkansas-pine bluff golden lions": "arkansas-pine-bluff-golden-lions",
  "bethune-cookman": "bethune-cookman-wildcats",
  "bethune-cookman wildcats": "bethune-cookman-wildcats",
  "florida a&m": "florida-a&m-rattlers",
  "florida a&m rattlers": "florida-a&m-rattlers",
  "grambling state": "grambling-state-tigers",
  "grambling state tigers": "grambling-state-tigers",
  "jackson state": "jackson-state-tigers",
  "jackson state tigers": "jackson-state-tigers",
  "mississippi valley state": "mississippi-valley-state-delta-devils",
  "mississippi valley state delta devils":
    "mississippi-valley-state-delta-devils",
  "prairie view a&m": "prairie-view-a&m-panthers",
  "prairie view a&m panthers": "prairie-view-a&m-panthers",
  southern: "southern-jaguars",
  "southern jaguars": "southern-jaguars",
  "texas southern": "texas-southern-tigers",
  "texas southern tigers": "texas-southern-tigers",

  // ---------------   MLB  ------------------------------------//
  // --- AL East ---
  "baltimore orioles": "baltimore-orioles",
  "boston red sox": "boston-red-sox",
  "new york yankees": "new-york-yankees",
  "tampa bay rays": "tampa-bay-rays",
  "toronto blue jays": "toronto-blue-jays",

  // --- AL Central ---
  "chicago white sox": "chicago-white-sox",
  "cleveland guardians": "cleveland-guardians",
  "detroit tigers": "detroit-tigers",
  "kansas city royals": "kansas-city-royals",
  "minnesota twins": "minnesota-twins",

  // --- AL West ---
  "houston astros": "houston-astros",
  "los angeles angels": "los-angeles-angels",
  "oakland athletics": "oakland-athletics",
  "seattle mariners": "seattle-mariners",
  "texas rangers": "texas-rangers",

  // --- NL East ---
  "atlanta braves": "atlanta-braves",
  "miami marlins": "miami-marlins",
  "new york mets": "new-york-mets",
  "philadelphia phillies": "philadelphia-phillies",
  "washington nationals": "washington-nationals",

  // --- NL Central ---
  "chicago cubs": "chicago-cubs",
  "cincinnati reds": "cincinnati-reds",
  "milwaukee brewers": "milwaukee-brewers",
  "pittsburgh pirates": "pittsburgh-pirates",
  "st. louis cardinals": "st-louis-cardinals",

  // --- NL West ---
  "arizona diamondbacks": "arizona-diamondbacks",
  "colorado rockies": "colorado-rockies",
  "los angeles dodgers": "los-angeles-dodgers",
  "san diego padres": "san-diego-padres",
  "san francisco giants": "san-francisco-giants",

  // --- NFL ---
  // AFC East
  "buffalo bills": "buffalo-bills",
  "miami dolphins": "miami-dolphins",
  "new england patriots": "new-england-patriots",
  "new york jets": "new-york-jets",

  // AFC North
  "baltimore ravens": "baltimore-ravens",
  "cincinnati bengals": "cincinnati-bengals",
  "cleveland browns": "cleveland-browns",
  "pittsburgh steelers": "pittsburgh-steelers",

  // AFC South
  "houston texans": "houston-texans",
  "indianapolis colts": "indianapolis-colts",
  "jacksonville jaguars": "jacksonville-jaguars",
  "tennessee titans": "tennessee-titans",

  // AFC West
  "denver broncos": "denver-broncos",
  "kansas city chiefs": "kansas-city-chiefs",
  "las vegas raiders": "las-vegas-raiders",
  "los angeles chargers": "los-angeles-chargers",

  // NFC East
  "dallas cowboys": "dallas-cowboys",
  "new york giants": "new-york-giants",
  "philadelphia eagles": "philadelphia-eagles",
  "washington commanders": "washington-commanders",

  // NFC North
  "chicago bears": "chicago-bears",
  "detroit lions": "detroit-lions",
  "green bay packers": "green-bay-packers",
  "minnesota vikings": "minnesota-vikings",

  // NFC South
  "atlanta falcons": "atlanta-falcons",
  "carolina panthers": "carolina-panthers",
  "new orleans saints": "new-orleans-saints",
  "tampa bay buccaneers": "tampa-bay-buccaneers",

  // NFC West
  "arizona cardinals": "arizona-cardinals",
  "los angeles rams": "los-angeles-rams",
  "san francisco 49ers": "san-francisco-49ers",
  "seattle seahawks": "seattle-seahawks",
};
